version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    logging:
      driver: none 

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=LISTENER_DOCKER://:29092,LISTENER_HOST://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_DOCKER://kafka:29092,LISTENER_HOST://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    logging:
      driver: none 

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: Sandbox Kafka Cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092            
      DYNAMIC_CONFIG_ENABLED: 'true'
    ports:
      - 8787:8080   
    depends_on:
      - kafka
    logging:
      driver: none 

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    depends_on:
      - kafka
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - KAFKA_BROKER_LIST=kafka:29092
      - KAFKA_GROUP_NAME=clickhouse

volumes:
  clickhouse-data: